#!/usr/bin/env python3

"""The ever glorious hello world program"""

def print_plain(who):
    who = "Darth Maul"
    print("hello " + who + "!")

def print_foreva():
    while True:
        print("hello " + who + "!")
    
if __name__ == '__main__':
    print_plain() 
